import { defineConfig } from 'vitest/config';

/**
 * One config, two projects, one coverage report.
 *
 * Coverage has to be measured across both suites in a single run or the numbers
 * lie in both directions: the unit suite never touches `routes.ts`, and the
 * integration suite never reaches the failure branches that need a stubbed
 * repository. Reporting them separately would show two incomplete pictures and
 * no way to merge them.
 *
 *   pnpm test:unit          fast, no database
 *   pnpm test:integration   real Postgres, real filesystem
 *   pnpm test:security      the security suite as its own gate
 *   pnpm test:coverage      all three, with the 100% gate enforced
 */
export default defineConfig({
  test: {
    // The integration project truncates one shared database between cases, so
    // nothing may run in parallel with it. The unit suite is ~300ms serially,
    // which is not worth a second worker to speed up.
    fileParallelism: false,
    maxWorkers: 1,
    testTimeout: 30_000,
    hookTimeout: 30_000,

    projects: [
      {
        test: {
          name: 'unit',
          environment: 'node',
          include: ['src/**/*.spec.ts', 'test/helpers/**/*.spec.ts', 'test/fixtures/**/*.spec.ts'],
          exclude: ['**/node_modules/**', '**/dist/**'],
        },
      },
      {
        test: {
          name: 'security',
          environment: 'node',
          include: ['test/security/**/*.spec.ts'],
          setupFiles: ['./test/setup.ts'],
          pool: 'forks',
        },
      },
      {
        test: {
          name: 'integration',
          environment: 'node',
          include: ['test/integration/**/*.spec.ts'],
          setupFiles: ['./test/setup.ts'],
          pool: 'forks',
        },
      },
    ],

    coverage: {
      provider: 'v8',
      reporter: ['text-summary', 'text', 'html', 'lcov'],
      reportsDirectory: './coverage',

      // Only our own application code. Everything excluded below is excluded
      // for a stated reason — see the README's coverage section.
      include: ['src/**/*.ts'],
      exclude: [
        // Generated by `prisma generate`. Not ours, not reviewed, regenerated
        // on every schema change.
        'src/generated/**',
        // Type-only: erased at compile time, so there is nothing to execute.
        'src/**/*.d.ts',
        // The process entry point: loads env, opens the pool, binds a port and
        // installs signal handlers. Covering it in-process would mean calling
        // `listen()` and `process.exit()` inside the test runner. Everything it
        // composes — buildApp, loadEnv, createDatabase — is covered directly.
        'src/main.ts',
        '**/*.spec.ts',
      ],

      // The gate. Branches are the one that matters: a file can sit at 100%
      // lines while an `else` has never executed.
      thresholds: {
        statements: 100,
        branches: 100,
        functions: 100,
        lines: 100,
      },
    },
  },
});
